version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  holy-cow.cyrhades.fr:
    image: anssi/fcsc2024-pwn-holy-cow:latest
    ports:
      - ${PORT_SSH}:4000
